name: Build and Push Docker Images

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment (dev, qas, prd)"
        required: true
        type: string
      version_suffix:
        description: "Version suffix (e.g., -beta, -alpha, or empty for production)"
        required: false
        type: string
        default: ""
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Read version from file
        id: get_version
        run: |
          if [ -f version ]; then
            version=$(cat version)
            echo "version=$version" >> $GITHUB_OUTPUT
          else
            echo "Version file not found!"
            exit 1
          fi

      - name: Build version tag
        id: build_tag
        run: |
          BASE_VERSION="${{ steps.get_version.outputs.version }}"
          SUFFIX="${{ inputs.version_suffix }}"

          if [ -n "$SUFFIX" ]; then
            TAG="${BASE_VERSION}${SUFFIX}${{ github.run_number }}"
          else
            TAG="${BASE_VERSION}"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push REST API Docker image
        run: |
          BACKEND_TAG="${{ secrets.docker_username }}/crypto-vault-rest-api:${{ steps.build_tag.outputs.tag }}"
          docker build -t $BACKEND_TAG -f cmd/crypto-vault-rest-api/Dockerfile .
          docker push $BACKEND_TAG

      - name: Build and push gRPC API Docker image
        run: |
          BACKEND_TAG="${{ secrets.docker_username }}/crypto-vault-grpc-api:${{ steps.build_tag.outputs.tag }}"
          docker build -t $BACKEND_TAG -f cmd/crypto-vault-grpc-api/Dockerfile .
          docker push $BACKEND_TAG
