on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go 1.25.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Remove previous SoftHSM artifacts
        run: |
          sudo rm -rf /usr/lib/softhsm /usr/lib/x86_64-linux-gnu/softhsm*
          sudo rm -rf ~/.config/softhsm2 /tmp/tokens /var/lib/softhsm /etc/softhsm
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl opensc softhsm2 libssl-dev libengine-pkcs11-openssl bc make

      - name: Start external services
        run: make compose-start-infra

      - name: Configure SoftHSM token directory
        run: |
          mkdir -vp ~/.config/softhsm2
          echo "directories.tokendir = /tmp/tokens" > ~/.config/softhsm2/softhsm2.conf
          mkdir -vp /tmp/tokens

      - name: Run unit and integration tests and check if code coverage is above 70 percent threshold
        run: make coverage-check
        env:
          SOFTHSM2_CONF: /home/runner/.config/softhsm2/softhsm2.conf

      - name: Stop external services
        run: make compose-stop
