name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go 1.25.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt make

          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
          go install golang.org/x/tools/cmd/goimports@v0.40.0

          sudo npm install -g prettier@3.7.4

          sudo pip3 install pre-commit --break-system-packages

      - name: Run checks
        run: |
          make checks

      - name: Check changes
        run: |
          status=$(git status --porcelain=v1)
          if [[ -n "$status" ]]; then
            git diff
            exit 1
          fi
