name: Check Git diffs

on:
  pull_request:
    branches: [main]

jobs:
  check-diffs:
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Go 1.25.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.x'

    - name: Install packages for with tools for auto-formatting and linting
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
        go install golang.org/x/tools/cmd/goimports@v0.40.0

    - name: Install APT packages
      run: |
        sudo apt-get update
        sudo apt-get install -y shfmt make
    
    - name: Install Prettier globally
      run: |
        sudo npm install -g prettier@3.7.4

    - name: Auto-format and lint Go
      run: make format-and-lint

    - name: Check diffs
      run: |
        status=$(git status --porcelain=v1)
        if [[ -n "$status" ]]; then
          git diff
          exit 1
        fi